### ISSUE TITLE
FTL Node Issue Tracker

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleCloudPlatform/runtimes-common#382]
This issue is to track the nodejs8 ftl work status:

Images:
- [x] Build reproducible ubuntu image: https://github.com/GoogleCloudPlatform/debian-docker/pull/98
- [x] Build ubuntu+build_essential image https://github.com/GoogleCloudPlatform/debian-docker/pull/106
- [x] Build reproducible nodejs8 image (node + ubuntu) https://github.com/GoogleCloudPlatform/debian-docker/pull/106
- [x] Build reproducible nodejs8 image + build_essential https://github.com/GoogleCloudPlatform/debian-docker/pull/106

Other:
- [x] Add integration tests for FTL example applications
- [ ] Create/get-feedback-on cloudbuild steps for each image
- [x] Implement cache busting
- [x] Support gcp-build script
- [x] Set entrypoint

Not a blocker:
- [ ] Switch FTL caching to be single layer instead of base_image + dep layer

**Comment by dlorenc** [comment]
Added a few.

**Comment by dlorenc** [comment]
Basically done here. We should setup a few official releases soon and get some feedback on them.

**Comment by nkubala** [comment]
@dlorenc @aaron-prindle can this be closed?

**Comment by aaron-prindle** [comment]
yes, all these tasks are done.  we can open a new tracker if need be.  closing
